### ISSUE TITLE
Please Update Soon

### ISSUE THREAD

**Issue by Rgvmhrmtur** [andrisutanto/PremierLeagueApp#1]
Hello Sir,
I think your app is very nice look , and simple, and then can you add favorite fragment in this your premier app ? Thank You  
I hope this app updated soon

**Comment by andrisutanto** [comment]
@Rgvmhrmtur will update as soon as possible

**Comment by Rgvmhrmtur** [comment]
nice work sir, i hope a few bug in this premier soon has been fixed ,thx

**Comment by andrisutanto** [comment]
Yes, still have a few bug. Will update after bug fixed.

**Comment by Rgvmhrmtur** [comment]
ok sir thank you
